### ISSUE TITLE
Video support?

### ISSUE THREAD

**Issue by seanwestfall** [zincarla/go-image-board#14]
This isn't so much a technical issue then just a product feature request if it isn't already available.

**Comment by zincarla** [comment]
Wow, I did not see this for a while. It should already support video files such as mpg, avi, webm. It doesn't do anything fancy though, just embeds a video element with an auto-detected mime. Browser support is an issue for video files, and not all browsers may support the types of videos uploaded. For video files, there is even ffmpeg support to auto-generate a thumbnail on upload.

**Comment by zincarla** [comment]
Documentation added on this in 10266a666f8e9db358317d0bf0aec124963df148
