### ISSUE TITLE
Foreign key constraint is incorrectly formed

### ISSUE THREAD

**Issue by chizutan5** [zincarla/go-image-board#17]
Hello, 
Github kindly deleted my previous, much more detailed writeup, without actually posting it, but I will form the basic information back here:

There seems to be an issue in your SQL queries when you are generating the default database, Upon first start after editing the pre generated config.json and then running the binary, I get this in the console:
```
2023/01/31 04:29:10 Tue Jan 31 04:29:10 UTC 2023 - 30 - templatecacheCacheTemplates - 0 - INFO - Added Templates; 19
2023/01/31 04:29:10 Tue Jan 31 04:29:10 UTC 2023 - 10 - MariaDBPlugin/InitDatabase - 0 - FAIL - Failed to get database version, assuming not installed. Will attempt to perform install.; Error 1146: Table 'imageboard.DBVersion' doesn't exist
2023/01/31 04:29:10 Tue Jan 31 04:29:10 UTC 2023 - 10 - MariaDBPlugin/performFreshDBInstall - 0 - FAIL - Failed to install database; Error 1005: Can't create table `imageboard`.`ImageTags` (errno: 150 "Foreign key constraint is incorrectly formed")
2023/01/31 04:29:10 Tue Jan 31 04:29:10 UTC 2023 - 10 - main/main - 0 - FAIL - Failed to connect to database. Will keep trying. ; Error 1005: Can't create table `imageboard`.`ImageTags` (errno: 150 "Foreign key constraint is incorrectly formed")
2023/01/31 04:29:10 Tue Jan 31 04:29:10 UTC 2023 - 30 - main/main - 0 - INFO - Temp server now listening
```
After trying some of your SQL queries from `MariaDBPlugin.go`, direct through mysql in the console, it appears the problem isn't on my side, although I'm not completely sure. However, I get the same output:
```
MariaDB [imageboard]> CREATE TABLE ImageTags (ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE, ImageID BIGINT UNSIGNED NOT NULL, TagID BIGINT UNSIGNED NOT NULL, LinkerID BIGINT UNSIGNED NOT NULL, LinkTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, UNIQUE INDEX ImageTagPair (TagID,ImageID), INDEX(ImageID), INDEX(LinkerID), CONSTRAINT fk_ImageTagsImageID FOREIGN KEY (ImageID) REFERENCES Images(ID), CONSTRAINT fk_ImageTagsTagID FOREIGN KEY (TagID) REFERENCES Tags(ID));
ERROR 1005 (HY000): Can't create table `imageboard`.`ImageTags` (errno: 150 "Foreign key constraint is incorrectly formed")
```
Nevertheless, putting `SET FOREIGN_KEY_CHECKS=0;` into mysql did allow me to run your queries, but I have no idea if this is actually a safe fix.
I did attempt to create the entire database through this method but it refused to let me create the procedures through the console for some apparant reason, but this might be my fault. I did get it to create a user account for me and upload an image, but it gave me an SQL error when attempting to delete it, and given what procedures actually are, it makes sense.

I am using Ubuntu Server 2204, Mariadb 10.6.11 (Fresh db, user with all perms except grant privs, utf8mb4). I'm not running the binary through docker and I'm proxing the requests with nginx. (but I imagine little of this matters)

Thanks.

**Comment by chizutan5** [comment]
I was able to install the DB with `SET GLOBAL FOREIGN_KEY_CHECKS=0` executed on the db before starting the binary. @zincarla

**Comment by zincarla** [comment]
Fixed the issue, I only tested this during an in-place upgrade, and not a fresh install. Had to re-order when tables were being made so the foreign keys were satisfied.
